backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: /img
site_url: https://jovial-hugle-ec6054.netlify.app
display_url: https://jovial-hugle-ec6054.netlify.app
logo_url: https://jovial-hugle-ec6054.netlify.app/klimatpodden-logo.svg
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    sortableFields: ["date"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          dateFormat: "YYYY-MM-DD",
          timeFormat: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
